### ISSUE TITLE
RULE_TYPE

### ISSUE THREAD

**Issue by konrd-ctrl** [IMISE/ocRuleTool#2]
Der Compiler kann Leerzeichen im RULE_TYPE nicht als Fehler identifizieren.
![image](https://github.com/IMISE/ocRuleTool/assets/79573599/b4f12d36-f231-48b3-93d3-10bd84374a0c)
Stattdessen bekommt man diese Fehlermeldung welche es schwer macht den tatsächlichen Fehler zu sehen.
`error in "Rules" line 9: invalid rule_type Expression `

**Comment by fmeineke** [comment]
Wurde bereits gefixed. Problem triit nicht mehr auf.
